repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Fix the sorting of imports.
    - id: ruff
      name: ruff-sort-imports
      args: [ --select, I, --fix ]
    # Run the formatter.
    - id: ruff-format
